// Mocks generated by Mockito 5.0.17 from annotations
// in imploop/test/page/task_list/todo/todo_edit_modal_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:imploop/domain/todo_type.dart' as _i4;
import 'package:imploop/service/todo_type_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [TodoTypeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoTypeService extends _i1.Mock implements _i2.TodoTypeService {
  MockTodoTypeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> hasAlreadyRegistered(String? name) =>
      (super.noSuchMethod(Invocation.method(#hasAlreadyRegistered, [name]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<_i4.TodoType?> add(String? name) => (super.noSuchMethod(
      Invocation.method(#add, [name]),
      returnValue: Future<_i4.TodoType?>.value()) as _i3.Future<_i4.TodoType?>);
  @override
  _i3.Future<List<_i4.TodoType>> fetchRegisteredTodoTypeList() =>
      (super.noSuchMethod(Invocation.method(#fetchRegisteredTodoTypeList, []),
              returnValue: Future<List<_i4.TodoType>>.value(<_i4.TodoType>[]))
          as _i3.Future<List<_i4.TodoType>>);
  @override
  _i3.Future<bool> existsTodoType(int? todoTypeId) =>
      (super.noSuchMethod(Invocation.method(#existsTodoType, [todoTypeId]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<_i4.TodoType?> get(int? todoTypeId) => (super.noSuchMethod(
      Invocation.method(#get, [todoTypeId]),
      returnValue: Future<_i4.TodoType?>.value()) as _i3.Future<_i4.TodoType?>);
  @override
  _i3.Future<_i4.TodoType?> getByTypeName(String? todoTypeName) =>
      (super.noSuchMethod(Invocation.method(#getByTypeName, [todoTypeName]),
              returnValue: Future<_i4.TodoType?>.value())
          as _i3.Future<_i4.TodoType?>);
}
